spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          url: https://github.com/NarinHorn/spring-cloud-config-repo.git
          default-label: main # branch name
          clone-on-start: true
server:
  port: 8890